### ISSUE TITLE
searx and faceted search

### ISSUE THREAD

**Issue by roscopecoltran** [ik9999/popupsearch#2]
Hi,

Hope you are all well !

I am working on some kind of web assistant and I was wondering if you tried to add searx.

I would like to extend popupsearch with some faceted search features to apply on live or cached results. It could be either from searx or any full text search engine (elasticsearch, bleve,...); the idea is to build an abstraction layer for filtering those data.

The idea would be to filter search results with the category return in the JSON:
eg: https://searx.site/?q=popupsearch&categories=general&language=de-DE&format=json&pretty=true 

I found those references for vue.js:
- https://github.com/InnerSearch/vue-innersearch
- https://github.com/itemsapi/itemsjs
- https://github.com/itemsapi/itemsapi

Do you have any thoughts or advices for building such vue.js based component ?

Cheers,
Rosco

**Comment by ik9999** [comment]
Hello.
Im not sure i can help you with it.
You can add search engines here:
https://github.com/ik9999/popupsearch/blob/master/src/popup/store/modules/SearchResults.js#L123
https://github.com/ik9999/popupsearch/tree/master/src/popup/search
https://github.com/ik9999/popupsearch/blob/master/src/settings/root.vue#L134
