### ISSUE TITLE
Error when using valueserp as the search engine

### ISSUE THREAD

**Issue by rp1231** [ik9999/popupsearch#26]
Getting this error when using valueserp as the search engine:
```
{"request_info":{"success":false,"message":"Supplied api_key is not valid"}}
```

**Comment by rp1231** [comment]
Also searx returns a blank page as well.
The only option that returns google search results is the google html option.

**Comment by ik9999** [comment]
It means your valueserp API key is not valid. You have to register on valueserp.com, fill up a balance and only then you'll be able to use it.

**Comment by rp1231** [comment]
Where exactly should I enter this api key?
I can't find a place to enter the api key.

**Comment by rp1231** [comment]
Sorry closed by mistake.

**Comment by ik9999** [comment]
![Screenshot from 2022-05-03 18-49-41](https://user-images.githubusercontent.com/6804575/166477466-53a65fd7-9cfe-43bc-a3f2-21609a93c2a8.png)
Here. In settings.

**Comment by rp1231** [comment]
Thanks,
That worked.
